name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
    - uses: actions/checkout@v4
      with:
        path: paawaniWebsite
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'paawaniWebsite/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: './paawaniWebsite'

    - name: Linting
      run: npm run lint
      working-directory: './paawaniWebsite'

    - name: Build project
      run: npm run build
      working-directory: './paawaniWebsite'
